#!/bin/sh
# Inspired from https://stackoverflow.com/a/40535565

if $(git status -s -uall)
then
  # run the unit tests, animal sniffer checks and detekt checks
  ./gradlew check detektTest
else
  echo "Repo is dirty, please commit or stash changes before pushing to remote."
  exit 1
fi
