format_version: 3
pipelines:
  "fluid":
    group: fluid
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        git: git@github.com:redgreenio/fluid.git
        blacklist:
          - README.md
    stages:
      - unit-tests:
          tasks:
            - exec:
                command: ./gradlew
                arguments:
                  - core:createEmptyDirsForTests
                  - clean
                  - test

      - animalsniffer-checks:
          tasks:
            - exec:
                command: ./gradlew
                arguments:
                  - check

      - library-artifacts:
          tasks:
            - exec:
                command: ./gradlew
                arguments:
                  - jar

      - cli-artifact:
          tasks:
            - exec:
                command: ./gradlew
                arguments:
                  - cli:shadowJar
